export enum DepartmentType {
  ADMINISTRATION = 'administration',
  TEACHING = 'teaching',
  MEDICAL = 'medical',
  COUNSELING = 'counseling',
  BOARDING = 'boarding',
  TRANSPORTATION = 'transportation',
  CATERING = 'catering',
  FACILITIES = 'facilities',
  SECURITY = 'security',
  FINANCE = 'finance',
  HR = 'hr',
  IT = 'it',
  LIBRARY = 'library',
  SPORTS = 'sports',
  ARTS = 'arts',
  EXAMINATIONS = 'examinations',
}