// Academia Pro - School Admin Types Index
// Export all school-admin related types

// Export original types
export * from './school-admin.types';

// Export new consolidated types with explicit exports to avoid conflicts
export type {
  IStudent,
  ICreateStudentDto,
  IUpdateStudentDto,
  ITransferStudentDto,
  IAssignClassDto,
  IPromotionRequestDto,
  IBulkImportRequestDto,
  IGraduationRequestDto,
  ITransferStudentRequestDto,
  IStudentStatistics,
  IStudentFilters,
  IStudentSearchParams,
  IStudentSearchResult,
  IBulkOperationResult,
  IPromotionResult,
  IBulkImportResult,
  IGraduationResult,
  ITransferResult,
} from './student.types';

export type {
  IStaff,
  ICreateStaffDto,
  IUpdateStaffDto,
  IStaffStatistics,
  IHRStatistics,
  IStaffFilters,
  IStaffSearchParams,
  IStaffSearchResult,
  IStaffPerformance,
  IStaffAttendance,
  IBulkCreateStaffDto,
  IBulkUpdateStaffDto,
  IBulkStaffOperationResult,
  IBulkCreateStaffResult,
  IBulkUpdateStaffResult,
  IBulkDeleteStaffResult,
} from './staff.types';

export type {
  ISubject,
  ICurriculum,
  IClass,
  ILearningObjective,
  ICreateSubjectDto,
  IUpdateSubjectDto,
  ICreateCurriculumDto,
  ICreateClassDto,
  ICreateLearningObjectiveDto,
  IAcademicStatistics,
  ISubjectFilters,
  ICurriculumFilters,
  IClassFilters,
  ISubjectSearchParams,
  ICurriculumSearchParams,
  IClassSearchParams,
  ISubjectSearchResult,
  ICurriculumSearchResult,
  IClassSearchResult,
  IAddSubjectToCurriculumDto,
  IAssignSubjectToClassDto,
  IAcademicPerformanceReport,
  IAdvancedAcademicStatistics,
  IAcademicYearStatus,
  IStudentAcademicData,
  IParentAcademicData,
  ITeacherAcademicData,
} from './academic.types';

export type {
  IAttendanceRecord,
  IMarkAttendanceDto,
  IBulkMarkAttendanceDto,
  IBulkUpdateAttendanceDto,
  IAttendanceStatistics,
  IStudentAttendanceSummary,
  IClassAttendanceReport,
  IAttendanceFilters,
  IAttendanceSearchParams,
  IAttendanceSearchResult,
  IAttendanceTrend,
  IAttendanceTrendsParams,
  IAttendanceAlert,
  IAttendanceAlertsParams,
  IExcuseStudentDto,
  IAttendanceReportGenerationDto,
  IAttendanceReportResult,
  IAttendanceByDateRangeParams,
  IBulkAttendanceOperationResult,
  IBulkMarkAttendanceResult,
  IBulkUpdateAttendanceResult,
} from './attendance.types';