import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/auth/sign-in');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('link', { name: 'Students' }).click();
  await expect(page.getByRole('main').locator('div').filter({ hasText: 'StudentsManage student information, enrollment, and academic recordsBulk' }).first()).toBeVisible();
  await page.getByRole('button', { name: 'Add Student' }).click();
  await page.getByRole('textbox', { name: 'First Name *' }).click();
  await page.getByRole('textbox', { name: 'First Name *' }).fill('Mariose');
  await page.getByRole('textbox', { name: 'First Name *' }).press('Tab');
  await page.getByRole('textbox', { name: 'Last Name *' }).fill('Millan');
  await page.getByRole('textbox', { name: 'Middle Name' }).click();
  await page.getByRole('textbox', { name: 'Middle Name' }).fill('Susan');
  await page.getByRole('button', { name: 'Date of Birth *' }).click();
  await page.getByRole('button', { name: 'Wednesday, September 3rd,' }).click();
  await page.getByRole('combobox', { name: 'Gender *' }).click();
  await page.getByRole('option', { name: 'Female' }).click();
  await page.getByRole('combobox', { name: 'Blood Group' }).click();
  await page.getByRole('option', { name: 'A+' }).click();
  await page.getByRole('combobox', { name: 'Phone Number' }).click();
  await page.getByRole('option', { name: '🇳🇬 Nigeria +' }).click();
  await page.getByRole('textbox', { name: 'Enter phone number' }).click();
  await page.getByRole('textbox', { name: 'Enter phone number' }).fill('8107876676');
  await page.getByRole('textbox', { name: 'Email Address' }).click();
  await page.getByRole('textbox', { name: 'Email Address' }).fill('mariose@gmai.com');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email Address' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Email Address' }).fill('mariose@gmail.com');
  await page.getByRole('textbox', { name: 'Street Address' }).click();
  await page.getByRole('textbox', { name: 'Street Address' }).fill('New avenue');
  await page.getByRole('textbox', { name: 'City' }).click();
  await page.getByRole('textbox', { name: 'City' }).fill('Mark');
  await page.getByRole('combobox').filter({ hasText: 'Nigeria' }).click();
  await page.getByRole('option', { name: 'Nigeria' }).click();
  await page.getByRole('combobox', { name: 'State' }).click();
  await page.getByRole('option', { name: 'Abia' }).click();
  await page.getByRole('textbox', { name: 'Postal Code' }).click();
  await page.getByRole('textbox', { name: 'Postal Code' }).fill('60001');
  await page.getByRole('tab', { name: 'Academic' }).click();
  await expect(page.getByLabel('Academic').locator('div').filter({ hasText: 'Academic InformationSet up' }).first()).toBeVisible();
  await page.getByRole('combobox').filter({ hasText: 'Primary (PRY)' }).click();
  await page.getByRole('option', { name: 'Junior Secondary (JSS)' }).click();
  await page.getByRole('combobox').filter({ hasText: 'JSS 1' }).click();
  await page.getByRole('option', { name: 'JSS 2' }).click();
  await page.getByRole('combobox').filter({ hasText: 'Section A' }).click();
  await page.getByRole('option', { name: 'Section B' }).click();
  await page.getByRole('combobox').filter({ hasText: 'Regular' }).click();
  await page.getByRole('option', { name: 'Regular' }).click();
  await page.getByRole('button', { name: 'Admission Date *' }).click();
  await page.getByRole('button', { name: 'Wednesday, September 10th,' }).click();
  await page.getByRole('checkbox', { name: 'Boarding Student' }).click();
  await page.getByRole('tab', { name: 'Guardians' }).click();
  await expect(page.getByText('Guardian InformationAdd parent or guardian contact detailsFatherFather\'s')).toBeVisible();
  await page.getByRole('textbox', { name: 'Father\'s Name' }).click();
  await page.getByRole('textbox', { name: 'Father\'s Name' }).fill('Sergio Markina');
  await page.getByRole('combobox', { name: 'Father\'s Phone' }).click();
  await page.getByRole('option', { name: '🇳🇬 Nigeria +' }).click();
  await page.locator('label').filter({ hasText: 'Father\'s Phone🇳🇬+' }).getByPlaceholder('Enter phone number').click();
  await page.locator('label').filter({ hasText: 'Father\'s Phone🇳🇬+' }).getByPlaceholder('Enter phone number').fill('8107876676');
  await page.getByRole('textbox', { name: 'Father\'s Email' }).click();
  await page.getByRole('textbox', { name: 'Father\'s Email' }).fill('sergio@yopmail.com');
  await page.getByRole('textbox', { name: 'Father\'s Occupation' }).click();
  await page.getByRole('textbox', { name: 'Father\'s Occupation' }).fill('Teacher');
  await page.getByRole('textbox', { name: 'Mother\'s Name' }).click();
  await page.getByRole('textbox', { name: 'Mother\'s Name' }).fill('Suse');
  await page.getByRole('combobox', { name: 'Mother\'s Phone' }).click();
  await page.getByRole('option', { name: '🇳🇬 Nigeria +' }).click();
  await page.locator('label').filter({ hasText: 'Mother\'s Phone🇳🇬+' }).getByPlaceholder('Enter phone number').click();
  await page.locator('label').filter({ hasText: 'Mother\'s Phone🇳🇬+' }).getByPlaceholder('Enter phone number').fill('8107876676');
  await page.getByRole('textbox', { name: 'Mother\'s Email' }).click();
  await page.getByRole('textbox', { name: 'Mother\'s Email' }).fill('sus@yopmail.com');
  await page.getByRole('textbox', { name: 'Mother\'s Occupation' }).click();
  await page.getByRole('textbox', { name: 'Mother\'s Occupation' }).fill('Seamstress');
  await page.getByRole('textbox', { name: 'Guardian\'s Name' }).click();
  await page.getByRole('textbox', { name: 'Guardian\'s Name' }).fill('Joe');
  await page.getByRole('combobox', { name: 'Guardian\'s Phone' }).click();
  await page.getByRole('option', { name: '🇳🇬 Nigeria +' }).click();
  await page.locator('label').filter({ hasText: 'Guardian\'s Phone🇳🇬+' }).getByPlaceholder('Enter phone number').click();
  await page.locator('label').filter({ hasText: 'Guardian\'s Phone🇳🇬+' }).getByPlaceholder('Enter phone number').fill('8107876676');
  await page.getByRole('textbox', { name: 'Guardian\'s Name' }).click();
  await page.getByRole('textbox', { name: 'Guardian\'s Name' }).fill('Joe Marine');
  await page.getByRole('textbox', { name: 'Relationship' }).click();
  await page.getByRole('textbox', { name: 'Relationship' }).fill('Aunt');
  await page.getByRole('textbox', { name: 'Guardian\'s Email' }).click();
  await page.getByRole('textbox', { name: 'Guardian\'s Email' }).fill('joe@yopmail.com');
  await page.getByRole('tab', { name: 'Medical' }).click();
  await expect(page.getByText('Medical InformationAdd medical details and emergency contactsAllergiesList any')).toBeVisible();
  await page.getByRole('textbox', { name: 'Allergies List any allergies' }).click();
  await page.getByRole('textbox', { name: 'Allergies List any allergies' }).fill('None');
  await page.getByRole('textbox', { name: 'Medications List current' }).click();
  await page.getByRole('textbox', { name: 'Medications List current' }).fill('None');
  await page.getByRole('textbox', { name: 'Medical Conditions List any' }).click();
  await page.getByRole('textbox', { name: 'Medical Conditions List any' }).fill('None');
  await page.getByRole('textbox', { name: 'Emergency Contact Name' }).click();
  await page.getByRole('textbox', { name: 'Emergency Contact Name' }).fill('Fluke Sashe');
  await page.getByRole('combobox', { name: 'Emergency Contact Phone' }).click();
  await page.getByRole('option', { name: '🇳🇬 Nigeria +' }).click();
  await page.locator('label').filter({ hasText: 'Emergency Contact Phone🇳🇬+' }).getByPlaceholder('Enter phone number').click();
  await page.locator('label').filter({ hasText: 'Emergency Contact Phone🇳🇬+' }).getByPlaceholder('Enter phone number').fill('8107785563');
  await page.getByRole('textbox', { name: 'Relationship to Student' }).click();
  await page.getByRole('textbox', { name: 'Relationship to Student' }).fill('Mother\'s Friend');
  await page.getByRole('textbox', { name: 'Doctor\'s Name' }).click();
  await page.getByRole('textbox', { name: 'Doctor\'s Name' }).fill('Barry Whine');
  await page.getByRole('combobox', { name: 'Doctor\'s Phone' }).click();
  await page.getByRole('option', { name: '🇳🇬 Nigeria +' }).click();
  await page.locator('label').filter({ hasText: 'Doctor\'s Phone🇳🇬+' }).getByPlaceholder('Enter phone number').click();
  await page.locator('label').filter({ hasText: 'Doctor\'s Phone🇳🇬+' }).getByPlaceholder('Enter phone number').fill('8108946672');
  await page.getByRole('textbox', { name: 'Clinic/Hospital' }).click();
  await page.getByRole('textbox', { name: 'Clinic/Hospital' }).fill('New jersey hospital');
  await page.getByRole('tab', { name: 'Review' }).click();
  await expect(page.getByText('Review & SubmitPlease review all information before submittingPersonal')).toBeVisible();
  await page.getByRole('button', { name: 'Create Student' }).click();
});