version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: academia-pro-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    networks:
      - academia-pro-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis-insight:
    image: redis/redisinsight:latest
    container_name: academia-pro-redis-insight
    restart: unless-stopped
    ports:
      - "5540:5540"
    depends_on:
      - redis
    networks:
      - academia-pro-network

volumes:
  redis_data:
    driver: local

networks:
  academia-pro-network:
    driver: bridge
    name: academia-pro-network